### ISSUE TITLE
run wpf sample app

### ISSUE THREAD

**Issue by flat-eric147** [kekyo/FlashCap#108]
When compiling and running the FlashCap.Wpf application I get a runtime error:

System.IO.FileLoadException: 'Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0

The only way to solve it was to add the package reference (latest version 6.0.0)
System.Runtime.CompilerServices.Unsafe
and update Epoxy.Wpf to the latest version 1.11.0

Happy to push the change if needed.

**Comment by kekyo** [comment]
Thanks for getting back to me!

Just to be sure, I made a diff with updated various package references at [feature/109](https://github.com/kekyo/FlashCap/pull/109), could you please try it?

**Comment by flat-eric147** [comment]
I just tried and it compiles and runs without issues. Thank you!

**Comment by kekyo** [comment]
Merged, thanks!
