### ISSUE TITLE
Blue screen error without stopping

### ISSUE THREAD

**Issue by 4hera** [kekyo/FlashCap#120]
Hi team,
If I stop the project via visual studio without stopping the captured device, I get a blue screen error on the computer. I think it's a general problem with Directshow.
Do you have any suggestions for this?
The error I get is "SYSTEM THREAD EXCEPTION NOT HANDLED"

**Comment by kekyo** [comment]
Thank you reached out!

In my opinion, the error means that the exception raised in the kernel mode driver thread was not caught.
Possible reasons are:

* A camera driver malfunction.
* Invalid response from the camera hardware.
* Hardware problem in the system (CPU/memory/chipset, etc.)

It is impossible to generate this error with the user mode process software we usually design. Therefore, I don't think the code you wrote is the cause.
