### ISSUE TITLE
After running StartAsync() on linux, executing StopAsync() and then StartAsync(), pixelBufferArrived will not be executed again. 

### ISSUE THREAD

**Issue by nir34** [kekyo/FlashCap#124]
But it works fine on window platform

**Comment by kekyo** [comment]
Sorry later, I was able to reproduce it in my environment. I will check it out.

**Comment by kekyo** [comment]
@nir34 On V4L2, I fixed some leaked mmap descriptor on stopper handler. Could you test on the `feature/124` branch?

**Comment by nir34** [comment]
thank you,it work perfect

**Comment by kekyo** [comment]
It's my pleasure. If you need anything else, please reopen.
