### ISSUE TITLE
How to do shrink memory when capturing from WebCam to WPF

### ISSUE THREAD

**Issue by fiery9711** [kekyo/FlashCap#135]
Hi everyone, I'm new user this library, thanks for all who made it. But i have problem when i use webcam and set image to WPF my program size grows up to 2-3GB RAM memory how i can solve this problem?

**Comment by flat-eric147** [comment]
I use FlashCap with WPF and I don't see such behavior. Being .net, perhaps it's not doing garbage collection, you might try to trigger the [garbage collector](https://learn.microsoft.com/en-us/dotnet/api/system.gc.collect?view=net-8.0#System_GC_Collect) explicitly and see if the situation improves. Perhaps also share some of your code? How does the WPF sample behave?

**Comment by kekyo** [comment]
Related #138

This fix will pool the buffers used by PixelBuffer. Using this specification and `ReferImage()` may improve on situations where GC occurs continuously.
