### ISSUE TITLE
FlashCap.Avalonia  using SKImage saves more memory than SKBitmap

### ISSUE THREAD

**Issue by yangjieshao** [kekyo/FlashCap#51]
use SKBitmap
![image](https://user-images.githubusercontent.com/3275834/236999942-be8f973c-565a-4330-986a-ddbeaac6b844.png)

use SKImage 
![image](https://user-images.githubusercontent.com/3275834/237000156-78fa98a1-0be7-4c47-878e-4553843ad828.png)

SkiaImageView.Avalonia 使用的是  [11.0.0-preview6](https://github.com/kekyo/SkiaImageView/pull/3)

**Comment by kekyo** [comment]
I will close it as I do not see any possible problem. If you have any additional topics, please open them.
